---
title: "git_00"
author: "Cyndhell Anne Pilarca"
date: "Year 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!-- Put the first five lines of a poem by Lewis Carrol in this section-->
’Twas brillig, and the slithy toves   
Did gyre and gimble in the wabe:    
All mimsy were the borogoves,   
And the mome raths outgrabe.    
“Beware the Jabberwock, my son!

## Second Verse
<!--Put the first five lines of a poem by Robert Frost in this section-->
Whose woods these are I think I know.      
His house is in the village though;       
He will not see me stopping here      
To watch his woods fill up with snow.           
My little horse must think it queer

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,    
      Shining with all his might:   
He did his very best to make    
      The billows smooth and bright —     
And this was odd, because it was    
      The middle of the night.    

The moon was shining sulkily,   
      Because she thought the sun   
Had got no business to be there   
      After the day was done —        
"It's very rude of him," she said,        
      "To come and spoil the fun."
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
In twilight's embrace, where dreams are born,   
I wander through a world of whispers forlorn.   
Where moonbeams dance on gossamer wings,    
And nightingales serenade the eve that sings.   

Beneath a canopy of stars' gentle sway,   
I find solace in the secrets they convey.   
Each shimmering light, a tale to unfold,    
Of love, of loss, of stories yet untold.    

The night sky, a canvas of infinite dreams,   
Where hope's resplendent tapestry gleams.     
A tapestry woven with threads of stardust,  
Binding hearts together, in love and in trust.    

As gentle zephyrs whisper their sweet refrain,    
I'm captivated by the night's alluring domain.    
The shadows whisper ancient lullabies,    
Caressing my soul as darkness softly lies.  


